/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rxjava;

public class App {
    public void getGreeting() {



        MainClass.init("huthth").fuck(
                string -> System.out.print(string)
        );


    }

    public static void main(String[] args) {
        new App().getGreeting();
    }
}
